name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python (for embedding script only)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (npm) - force no rebuild
        run: |
          npm install --ignore-scripts
          npm config set target_arch x64
          npm config set node_gyp ""

      - name: Setup Python embedded (download, extract, pip, requirements)
        run: node scripts/embed-python-win.js

      - name: Use embedded Python for build
        run: |
          echo "PYTHON=%CD%\src\python-embed\python.exe" >> $GITHUB_ENV
        shell: cmd

      - name: Build Electron app (Windows)
        run: npx electron-builder --win --x64
        env:
          PYTHON: ${{ github.workspace }}\src\python-embed\python.exe
          npm_config_node_gyp: ""
          ELECTRON_REBUILD: false
          npm_config_rebuild: false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scripta-image-processing-win
          path: dist/*.exe