name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create hardcoded Python path for electron-builder
        run: |
          New-Item -ItemType Directory -Path "C:\usr\bin" -Force
          Copy-Item "${{ env.pythonLocation }}\python.exe" -Destination "C:\usr\bin\python.exe"

      - name: Install dependencies (npm)
        run: npm install --ignore-scripts

      - name: Build Electron app (Windows)
        run: npx electron-builder --win --x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scripta-image-processing-win
          path: dist/*.exe